/* eslint-disable */
const countryMap = {
	'Mainland China': 'China',
	'Thailand': 'Asia',
	'Japan': 'Japan',
	'South Korea': 'Asia',
	'Taiwan': 'Asia',
	'US': 'North America',
	'Macau': 'China',
	'Hong Kong': 'China',
	'Singapore': 'Asia',
	'Vietnam': 'Asia',
	'France': 'Europe',
	'Nepal': 'Asia',
	'Malaysia': 'Asia',
	'Canada': 'North America',
	'Australia': 'Australia',
	'Cambodia': 'Asia',
	'Sri Lanka': 'Asia',
	'Germany': 'Europe',
	'Finland': 'Europe',
	'United Arab Emirates': 'Asia',
	'Philippines': 'Asia',
	'India': 'Asia',
	'Italy': 'Europe',
	'UK': 'Europe',
	'Russia': 'Asia',
	'Sweden': 'Europe',
	'Spain': 'Europe',
	'Belgium': 'Europe',
	'Others': 'Others',
	'Egypt': 'Africa',
	'Iran': 'Asia',
	'Lebanon': 'Asia',
	'Iraq': 'Asia',
	'Oman': 'Asia',
	'Afghanistan': 'Asia',
	'Bahrain': 'Asia',
	'Kuwait': 'Asia',
	'Algeria': 'Africa',
	'Croatia': 'Europe',
	'Switzerland': 'Europe',
	'Austria': 'Europe',
	'Israel': 'Asia',
	'Pakistan': 'Asia',
	'Brazil': 'South America',
	'Georgia': 'Asia',
	'Greece': 'Europe',
	'North Macedonia': 'Europe',
	'Norway': 'Europe',
	'Romania': 'Europe',
	'Denmark': 'Europe',
	'Estonia': 'Europe',
	'Netherlands': 'Europe',
	'San Marino': 'Europe',
	'Belarus': 'Europe',
	'Iceland': 'Europe',
	'Lithuania': 'Europe',
	'Mexico': 'South America',
	'New Zealand': 'Australia',
	'Nigeria': 'Africa',
	'Ireland': 'Europe',
	'Luxembourg': 'Europe',
	'Monaco': 'Europe',
	'Qatar': 'Asia',
	'Ecuador': 'South America',
	'Azerbaijan': 'Asia',
	'Czech Republic': 'Europe',
	'Armenia': 'Asia',
	'Dominican Republic': 'North America',
	'Indonesia': 'Asia',
	'Portugal': 'Europe',
	'Andorra': 'Europe',
	'Latvia': 'Europe',
	'Morocco': 'Africa',
	'Saudi Arabia': 'Asia',
	'Senegal': 'Africa'
  }
  
module.exports = countryMap
